config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [] do
    collection do
      patch "profile", to: "users#update_profile", as: :profile
      get :profile, to: "users#profile"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [ :index, :show ] do
    resources :favourites, only: [:create, :destroy]
    resources :reviews, only: [ :index, :create ]
  end
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :dish_ingredients
  has_many :ingredients, through: :dish_ingredients
  has_one_attached :photo
  validates :name, presence: true, uniqueness: { scope: :restaurant_id }
end

app/models/dish_ingredient.rb
class DishIngredient < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  validates :restaurant, uniqueness: { scope: :user }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :ingredient_category
  validates :name, presence: true
end

app/models/ingredient_category.rb
class IngredientCategory < ApplicationRecord
  validates :name, presence: true
  has_many :ingredients
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  has_many :dishes
  has_many :ingredients
  has_many :favourites
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :allergies
  has_many :ingredients, through: :allergies
  has_many :favourites
  has_many :restaurants, through: :favourites
  has_one_attached :photo
  accepts_nested_attributes_for :allergies, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: :profile
  def default_url_options
    { host: ENV["https://www.whatsin.digital/"] || "localhost:3000" }
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_restaurant, only: [:create, :destroy]

  def index
    @favourites = Favourite.all
  end

  def new
    @favourite = Favourite.new
  end

  def create
    @favourite = Favourite.new
    @favourite.restaurant = @restaurant
    @favourite.user = current_user
    @favourite.save
    respond_to do |f|
      f.html { redirect_to restaurant_path(@restaurant) }
      f.text {
        render partial: "favourites/link_destroy_favourite.html.erb",
               locals: {
                 restaurant: @restaurant,
                 favourite: @favourite
       }
      }
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    respond_to do |f|
      f.html { redirect_to restaurant_path(@restaurant) }
      f.text { render partial: "favourites/link_favourite.html.erb", locals: { restaurant: @restaurant, favourite: @favourite }}
    end
  end

  private


  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @user_favourites = current_user&.favourites.to_a
    if params[:user].present? && ingredient_params[:ingredient_ids].present?
      @ingredients_query = ingredient_params[:ingredient_ids]
      @dishes = Dish.joins(
        :dish_ingredients
      ).where.not("dish_ingredients.ingredient_id IN (?)", ingredient_params[:ingredient_ids])
      @restaurants = Restaurant.joins(:dishes).where(dishes: { id: @dishes.pluck(:id) }).distinct

    # SELECT DISTINCT * restaurants JOINS dishes on dishes.restaurant_id = restaurants.id
    # WHERE dishes.id IN (1, 3, 4, 5)
    elsif user_signed_in? && !current_user.ingredients.empty?
      @ingredients_query = current_user.ingredients.pluck(:id)
      @dishes = Dish.joins(
        :dish_ingredients
      ).where.not("dish_ingredients.ingredient_id IN (?)", @ingredients_query)
      @restaurants = Restaurant.joins(:dishes).where(dishes: { id: @dishes.pluck(:id) }).distinct
    else
      @restaurants = Restaurant.all
    end

    if params[:address]
      @restaurants = @restaurants.near(params[:address], 1.5)
    end
    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        info_window: render_to_string(partial: "info_window", locals: { restaurant: restaurant }),
      }
    end
  end

  def show
    if params[:user].present? && params[:user][:ingredient_ids].present?
      @ingredients_query = ingredient_params[:ingredient_ids]
      @dishes = @restaurant.dishes.joins(
        :dish_ingredients
      ).where.not("dish_ingredients.ingredient_id IN (?)", ingredient_params[:ingredient_ids])
    else
      @dishes = @restaurant.dishes.includes(dish_ingredients: :ingredient)
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name, :address, :photo, :category, :rating, :price, :wifi,
      :adaptability, :start_time, :end_time
    )
  end

  def ingredient_params
    params.require(:user).permit(ingredient_ids: [])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update_profile
    if params[:user]
      current_user.allergies.destroy_all
      current_user.update!(user_params)
      redirect_to restaurants_path, notice: "Updated profile with undesired ingredients."
    end
  end

  def profile
  end

  private

  def user_params
    params.require(:user).permit(ingredient_ids: [])
  end

  def ingredient_params
    params.require(:save).permit(ingredients: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/favourites/_link_destroy_favourite.html.erb
<%= link_to restaurant_favourite_path(restaurant, favourite), data: { controller: "favourite", action: "click->favourite#deleteFavouriteRestaurant" } do %>
  <div class="heart"  data-favourites-target="favourite"><i class="fas fa-heart selected-heart"></i></div>
<% end %>

app/views/favourites/_link_favourite.html.erb
<%= link_to restaurant_favourites_path(restaurant), data: { controller: "favourite", action: "click->favourite#favouriteRestaurant" } do %>
          <div class="heart"  data-favourites-target="favourite"><i class="far fa-heart border-heart"></i></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Flavicon link -->
   <%= favicon_link_tag%>

   <!-- Social Meta tags data-->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!--Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="min <%= "main-container" if current_page?(root_path)%>">
      <%= yield %>

    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="fun">Making <strong> Eating </strong> out <strong> easier</strong>!</h1>
  <h2 class="home-grey">Working to make your meals safe and allergen free.</h2>
</div>
  <div class="form-container">
    <form action="/restaurants" method="get" data-controller="geocoder"  data-geocoder-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>" class="search-container">
      <div data-geocoder-target="container"></div>
      <input type="text" name="address" placeholder="Type your address!"
              data-geocoder-target="address" class="d-none">
      <input type="submit" value="Go" class="btn" id="go">
    </form>
  </div>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%=# f.input :name %>

  <%= f.input :address,
              input_html: { data: { geocoder_target: "address" } },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/index.html.erb
<details class="details">
<summary class="color_ingredient">What can't you eat?</summary>
    <%= simple_form_for current_user || User.new, url: "/restaurants", method: "GET" do |f| %>
  <div class="ing-cat-container">
    <% IngredientCategory.all.each do |cat| %>
      <h2 class="category-name"> <%= cat.name.capitalize %></h2>
    <%= f.input :ingredient_ids, legend_tag: false, collection: cat.ingredients, as: :check_boxes,
              include_hidden:false, include_blank: false, input_html: { class: "tag-selector" },
              label_html: { class: "d-none" },
              item_wrapper_class: 'tag-item', checked: @ingredients_query %>
          <% end %>
  </div>
  <%= f.submit "Filter", class: "btn", id: "filter" %>
  <% end %>
</details>


<div style="width: 100%; height: 250px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<% if @restaurants %>
  <% @restaurants.each do |restaurant| %>
      <div class="card-trip">
        <div id="card-photo"style="background-image: url('<%= cl_image_path restaurant.photo.key %>')">
          <% if user_signed_in? %>
            <% favourite = @user_favourites.find { |favourite| favourite.restaurant_id == restaurant.id } %>
            <% if favourite %>
            <%= render 'favourites/link_destroy_favourite', restaurant: restaurant, favourite: favourite %>
            <% else %>
            <%= render 'favourites/link_favourite', restaurant: restaurant %>
            <% end %>
          <% end %>
        </div>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to restaurant.name, restaurant_path(restaurant, user: {ingredient_ids: @ingredients_query}, address: params[:address]), class:"rest-name-card" %></h2>
            <p><%= restaurant.category %></p>
          </div>
          <strong class="card-trip-pricing"><i class="fas fa-star star"></i><%= restaurant.rating %></strong>
        </div>
      </div>
    <% end %>
<% end %>

app/views/restaurants/show.html.erb
<div class="show-main-container">
  <div class="show-banner" style="background-image: url(<%= cl_image_path @restaurant.photo.key, height: 300, width: 400, crop: :fill if @restaurant.photo.attached? %>)">
    <h1 class="rest-name-show"><%= @restaurant.name %></h1>
  </div>
  <div class="container">
    <div class="card-trip show-info">
      <div class="first-row">
        <div class="top-info">
          <h2 id="price"><%= @restaurant.price %></h2>
          <h2 class= "restaurant-category"><%= @restaurant.category %></h2>
          <h2 class="card-trip-pricing"><i class="fas fa-star star"></i><%= @restaurant.rating %></h2>
        </div>

        <div>
          <h2><%= @restaurant.address %></h2>
        </div>

        <div class="hour">
          <p><strong><%= @restaurant.start_time %>:00 PM - <%= @restaurant.end_time %>:00 PM</strong></p>
        </div>

        <div class="icon-wrapper">
          <% if @restaurant.wifi %>
            <div class="icon-description">
              <img id="icon" src="https://img.icons8.com/windows/32/000000/wifi--v2.png"/>
              <figcaption>Wifi</figcaption>
            </div>
          <% else %>
            <div class="icon-description">
              <img id="icon" src="https://img.icons8.com/plumpy/24/000000/without-internet.png"/>
              <figcaption>Wifi</figcaption>
            </div>
          <% end %>
          <% if @restaurant.terrace %>
            <div class="icon-description">
              <img src="https://cdn-icons-png.flaticon.com/512/358/358824.png"/>
              <figcaption>Terrace</figcaption>
            </div>
          <% else %>
            <div class="icon-description">
              <img id="icon" src="https://cdn-icons-png.flaticon.com/512/358/358824.png"/>
              <figcaption>Terrace</figcaption>
            </div>
          <% end %>
        </div>

        <div class="available">
          <% if @restaurant.adaptability %>
            <p class="red">This restaurant will <strong>Not</strong> change ingredients.</p>
          <% else %>
            <p class="green">This restaurant <strong>Can</strong> make changes to your ingredients. </p>
          <% end %>
        </div>
          </div>
        <a class="btn" href="tel:<%= @restaurant.telephone %>">Contact the restaurant</a>
      </div>
    <div>
      <h2> These are the dishes you can eat! </h2>
    </div>
    <% @dishes.each do |dish| %>
      <div class="card-product">
      <%= cl_image_tag dish.photo.key, height: 100, width: 100, crop: :fill if dish.photo.attached? %>
        <div class="card-product-infos">
          <h2><%= dish.name%></h2>
          <% dish.ingredients.each do |ingredient| %>
            <%= ingredient.name  %>
          <% end %>
        </div>
      </div>
      <% end %>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%="home-navbar" if current_page?(root_path)%>">
  <div class="container-fluid">
  <% if @restaurant && current_page?(restaurant_path(@restaurant)) %>
    <%= link_to  restaurants_path(@restaurant, user: {ingredient_ids: @ingredients_query}, address: params[:address]) do %>
      <i class="fas fa-chevron-circle-left back"></i>
    <% end %>
    <% else%>
    <div></div>
  <%end%>


    <%= link_to "WhatsIn?", root_path, class: "logo" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <?xml version="1.0" ?><!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'><svg class="menu-burger" height="32px" id="Layer_1" style="enable-background:new 0 0 32 32;" version="1.1" viewBox="0 0 32 32" width="32px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M4,10h24c1.104,0,2-0.896,2-2s-0.896-2-2-2H4C2.896,6,2,6.896,2,8S2.896,10,4,10z M28,14H4c-1.104,0-2,0.896-2,2  s0.896,2,2,2h24c1.104,0,2-0.896,2-2S29.104,14,28,14z M28,22H4c-1.104,0-2,0.896-2,2s0.896,2,2,2h24c1.104,0,2-0.896,2-2  S29.104,22,28,22z"/></svg>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
              <%= link_to "Preferences", profile_users_path(current_user), class: "nav-link" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="details">
  <div class="profile-container">
    <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar" %>
    <p>Please, set your preferences.</p>
  </div>
  <h3 class="color_ingredient">What can't you eat?</h3>

    <div class="profile-details">
    </div>
 <%= simple_form_for current_user, url: :profile_users, method: "PATCH" do |f| %>
  <div class="ing-cat-container">
    <% IngredientCategory.all.each do |cat| %>
      <h2 class="category-name"> <%= cat.name.capitalize %></h2>
    <%= f.input :ingredient_ids, legend_tag: false, collection: cat.ingredients, as: :check_boxes,
              include_hidden:false, include_blank: false, input_html: { class: "tag-selector" },
              label_html: { class: "d-none" },
              item_wrapper_class: 'tag-item' %>
          <%end %>
  </div>
    <%= f.submit "Save your allergens", class: "btn" %>
    <% end %>

</div>

app/views/users/show.html.erb
 <%= simple_form_for :save, url: `/users/#{current_user.id}`, method: "PATCH" do |f| %>
    <% IngredientCategory.all.each do |cat| %>
      <h2 class="category-name"> <%= cat.name.capitalize %></h2>
    <%= f.input :ingredients, legend_tag: false, collection: cat.ingredients, as: :check_boxes,
              include_hidden:false, include_blank: false, input_html: { class: "tag-selector" },
              label_html: { class: "d-none" },
              item_wrapper_class: 'tag-item' %>
          <%end %>
  </div>
  <%= f.submit "Save your ingredients", class: "btn" %>
  <% end %>